version: '3.8'

# https://redis.io/docs/install/install-redisinsight/install-on-docker/
# https://hub.docker.com/r/redis/redisinsight
services:
  redisinsight:
    image: redis/redisinsight:2.46
    hostname: redisinsight
    ports:
      - 5540:5540
    volumes:
      - redisinsight_data:/data
    networks:
      - backend_network

volumes:
  redisinsight_data:

networks:
  backend_network:
