{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redisinsight.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redisinsight.labels" . | nindent 4 }}
  {{- with .Values.service.headless.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  ports:
    - port: 5540
      targetPort: http-ui
      protocol: TCP
      name: http-ui
  selector:
    {{- include "redisinsight.selectorLabels" . | nindent 4 }}
{{- end }}